lib/our_home_web/router.ex
defmodule OurHomeWeb.Router do
  use OurHomeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {OurHomeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", OurHomeWeb do
    pipe_through :browser

    get "/", HomeController, :index

    post "/", AdblockerController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", OurHomeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: OurHomeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/our_home_web/controllers/home_controller.ex
defmodule OurHomeWeb.HomeController do
  use OurHomeWeb, :controller

  def index(conn, _params) do
    assigns = [
      adblocker: OurHome.Pihole.summary()
    ]

    render(conn, "index.html", assigns)
  end
end

lib/our_home_web/views/home_view.ex
defmodule OurHomeWeb.HomeView do
  use OurHomeWeb, :view
end

lib/our_home_web/templates/home/_action_adblocker.html.heex
<%= case @adblocker.status do %>
  <% "enabled" -> %>
    <div class="my-3 flex justify-between">
      <div>
        <div class="text-bold text-xl leading-none">Ad Blocker</div>
        <div class="-mt-0.5 flex items-center">
          <div class="h-2 w-2 mt-x mr-1 rounded-full bg-emerald-600 opacity-50"></div>
          <div class="opacity-70">enabled</div>
        </div>
      </div>

      <%= form_for :adblocker, Routes.adblocker_path(@conn, :create), fn f -> %>
        <%= hidden_input f, :action, value: "disable" %>
        <%= hidden_input f, :time, value: "1800" %>
        <%= submit "Disable", class: "h-10 w-22 flex justify-center items-center border-2 rounded border-rose-300 text-rose-700 bg-rose-100 opacity-50 uppercase font-bold text-xs tracking-wider hover:opacity-80" %>
      <% end %>
    </div>

  <% "disabled" -> %>
    <div class="my-3 flex justify-between">
      <div>
        <div class="text-bold text-xl leading-none">Ad Blocker</div>
        <div class="-mt-0.5 flex items-center">
          <div class="h-2 w-2 mt-x mr-1 rounded-full bg-rose-600 opacity-50"></div>
          <div class="opacity-70">disabled</div>
        </div>
      </div>

      <%= form_for :adblocker, Routes.adblocker_path(@conn, :create), fn f -> %>
        <%= hidden_input f, :action, value: "enable" %>
        <%= submit "Enable", class: "h-10 w-22 flex justify-center items-center border-2 rounded border-emerald-300 text-emerald-700 bg-emerald-100 opacity-50 uppercase font-bold text-xs tracking-wider hover:opacity-80" %>
      <% end %>
    </div>

  <% _ -> %>
    <div class="my-3 flex justify-between">
      <div>
        <div class="text-bold text-xl leading-none">Ad Blocker</div>
        <div class="-mt-0.5 flex items-center">
          <div class="h-2 w-2 mt-x mr-1 rounded-full bg-gray-300"></div>
          <div class="opacity-70">offline</div>
        </div>
      </div>
    </div>
<% end %>

lib/our_home_web/templates/home/_actions.html.heex
<div class="mt-6 w-96 md:w-30rem xl:w-48rem">
  <div class="mb-3 text-fuchsia-800 opacity-50 uppercase font-bold text-sm tracking-wider">Actions</div>

  <div class="grid grid-cols-1 xl:grid-cols-3 gap-x-8">
    <%= render "_action_adblocker.html", assigns %>
  </div>
</div>

lib/our_home_web/templates/home/index.html.heex
<%= render "_actions.html", assigns %>

<div class="mt-6 w-96 md:w-30rem xl:w-48rem">
  <div class="mb-3 text-fuchsia-800 opacity-50 uppercase font-bold text-sm tracking-wider">Admin Panels</div>

  <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-y-2 gap-x-2">
    <a href="http://pihole.home/admin" class="group p-4 pb-3 w-full flex border-2 rounded border-stone-200 text-slate-700 bg-stone-50 hover:border-blue-200">
      <div class="flex">
        <svg class="h-6 w-6 mt-0.5 mr-1.5 opacity-80" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="M12.5858 4.58579C13.3668 3.80474 14.6331 3.80474 15.4142 4.58579C16.1952 5.36683 16.1952 6.63316 15.4142 7.41421L12.4142 10.4142C11.6331 11.1953 10.3668 11.1953 9.58577 10.4142C9.19524 10.0237 8.56208 10.0237 8.17156 10.4142C7.78103 10.8047 7.78103 11.4379 8.17156 11.8284C9.73365 13.3905 12.2663 13.3905 13.8284 11.8284L16.8284 8.82843C18.3905 7.26633 18.3905 4.73367 16.8284 3.17157C15.2663 1.60948 12.7337 1.60948 11.1716 3.17157L9.67156 4.67157C9.28103 5.0621 9.28103 5.69526 9.67156 6.08579C10.0621 6.47631 10.6952 6.47631 11.0858 6.08579L12.5858 4.58579ZM7.58579 9.58579C8.36683 8.80474 9.63316 8.80474 10.4142 9.58579C10.8047 9.97631 11.4379 9.97631 11.8284 9.58579C12.219 9.19526 12.219 8.5621 11.8284 8.17157C10.2663 6.60948 7.73367 6.60948 6.17157 8.17157L3.17157 11.1716C1.60948 12.7337 1.60948 15.2663 3.17157 16.8284C4.73367 18.3905 7.26633 18.3905 8.82843 16.8284L10.3284 15.3284C10.719 14.9379 10.719 14.3047 10.3284 13.9142C9.9379 13.5237 9.30474 13.5237 8.91421 13.9142L7.41421 15.4142C6.63316 16.1953 5.36684 16.1953 4.58579 15.4142C3.80474 14.6332 3.80474 13.3668 4.58579 12.5858L7.58579 9.58579Z" fill-rule="evenodd"/></svg>
        <div>
          <div class="text-sm font-bold uppercase tracking-wide">Ad Blocker</div>
          <div class="text-xs text-slate-500 group-hover:text-blue-600">pihole.home/admin</div>
        </div>
      </div>
    </a>

    <a href="http://moments.home" class="group p-4 pb-3 w-full flex border-2 rounded border-stone-200 text-slate-700 bg-stone-50 hover:border-blue-200">
      <div class="flex">
        <svg class="h-6 w-6 mt-0.5 mr-1.5 opacity-80" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="M12.5858 4.58579C13.3668 3.80474 14.6331 3.80474 15.4142 4.58579C16.1952 5.36683 16.1952 6.63316 15.4142 7.41421L12.4142 10.4142C11.6331 11.1953 10.3668 11.1953 9.58577 10.4142C9.19524 10.0237 8.56208 10.0237 8.17156 10.4142C7.78103 10.8047 7.78103 11.4379 8.17156 11.8284C9.73365 13.3905 12.2663 13.3905 13.8284 11.8284L16.8284 8.82843C18.3905 7.26633 18.3905 4.73367 16.8284 3.17157C15.2663 1.60948 12.7337 1.60948 11.1716 3.17157L9.67156 4.67157C9.28103 5.0621 9.28103 5.69526 9.67156 6.08579C10.0621 6.47631 10.6952 6.47631 11.0858 6.08579L12.5858 4.58579ZM7.58579 9.58579C8.36683 8.80474 9.63316 8.80474 10.4142 9.58579C10.8047 9.97631 11.4379 9.97631 11.8284 9.58579C12.219 9.19526 12.219 8.5621 11.8284 8.17157C10.2663 6.60948 7.73367 6.60948 6.17157 8.17157L3.17157 11.1716C1.60948 12.7337 1.60948 15.2663 3.17157 16.8284C4.73367 18.3905 7.26633 18.3905 8.82843 16.8284L10.3284 15.3284C10.719 14.9379 10.719 14.3047 10.3284 13.9142C9.9379 13.5237 9.30474 13.5237 8.91421 13.9142L7.41421 15.4142C6.63316 16.1953 5.36684 16.1953 4.58579 15.4142C3.80474 14.6332 3.80474 13.3668 4.58579 12.5858L7.58579 9.58579Z" fill-rule="evenodd"/></svg>
        <div>
          <div class="text-sm font-bold uppercase tracking-wide">Moments</div>
          <div class="text-xs text-slate-500 group-hover:text-blue-600">moments.home</div>
        </div>
      </div>
    </a>

    <a href="http://homebridge.home" class="group p-4 pb-3 w-full flex border-2 rounded border-stone-200 text-slate-700 bg-stone-50 hover:border-blue-200">
      <div class="flex">
        <svg class="h-6 w-6 mt-0.5 mr-1.5 opacity-80" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="M12.5858 4.58579C13.3668 3.80474 14.6331 3.80474 15.4142 4.58579C16.1952 5.36683 16.1952 6.63316 15.4142 7.41421L12.4142 10.4142C11.6331 11.1953 10.3668 11.1953 9.58577 10.4142C9.19524 10.0237 8.56208 10.0237 8.17156 10.4142C7.78103 10.8047 7.78103 11.4379 8.17156 11.8284C9.73365 13.3905 12.2663 13.3905 13.8284 11.8284L16.8284 8.82843C18.3905 7.26633 18.3905 4.73367 16.8284 3.17157C15.2663 1.60948 12.7337 1.60948 11.1716 3.17157L9.67156 4.67157C9.28103 5.0621 9.28103 5.69526 9.67156 6.08579C10.0621 6.47631 10.6952 6.47631 11.0858 6.08579L12.5858 4.58579ZM7.58579 9.58579C8.36683 8.80474 9.63316 8.80474 10.4142 9.58579C10.8047 9.97631 11.4379 9.97631 11.8284 9.58579C12.219 9.19526 12.219 8.5621 11.8284 8.17157C10.2663 6.60948 7.73367 6.60948 6.17157 8.17157L3.17157 11.1716C1.60948 12.7337 1.60948 15.2663 3.17157 16.8284C4.73367 18.3905 7.26633 18.3905 8.82843 16.8284L10.3284 15.3284C10.719 14.9379 10.719 14.3047 10.3284 13.9142C9.9379 13.5237 9.30474 13.5237 8.91421 13.9142L7.41421 15.4142C6.63316 16.1953 5.36684 16.1953 4.58579 15.4142C3.80474 14.6332 3.80474 13.3668 4.58579 12.5858L7.58579 9.58579Z" fill-rule="evenodd"/></svg>
        <div>
          <div class="text-sm font-bold uppercase tracking-wide">Homebridge</div>
          <div class="text-xs text-slate-500 group-hover:text-blue-600">homebridge.home</div>
        </div>
      </div>
    </a>

    <a href="http://synology.home" class="group p-4 pb-3 w-full flex border-2 rounded border-stone-200 text-slate-700 bg-stone-50 hover:border-blue-300">
      <div class="flex">
        <svg class="h-6 w-6 mt-0.5 mr-1.5 opacity-80" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="M12.5858 4.58579C13.3668 3.80474 14.6331 3.80474 15.4142 4.58579C16.1952 5.36683 16.1952 6.63316 15.4142 7.41421L12.4142 10.4142C11.6331 11.1953 10.3668 11.1953 9.58577 10.4142C9.19524 10.0237 8.56208 10.0237 8.17156 10.4142C7.78103 10.8047 7.78103 11.4379 8.17156 11.8284C9.73365 13.3905 12.2663 13.3905 13.8284 11.8284L16.8284 8.82843C18.3905 7.26633 18.3905 4.73367 16.8284 3.17157C15.2663 1.60948 12.7337 1.60948 11.1716 3.17157L9.67156 4.67157C9.28103 5.0621 9.28103 5.69526 9.67156 6.08579C10.0621 6.47631 10.6952 6.47631 11.0858 6.08579L12.5858 4.58579ZM7.58579 9.58579C8.36683 8.80474 9.63316 8.80474 10.4142 9.58579C10.8047 9.97631 11.4379 9.97631 11.8284 9.58579C12.219 9.19526 12.219 8.5621 11.8284 8.17157C10.2663 6.60948 7.73367 6.60948 6.17157 8.17157L3.17157 11.1716C1.60948 12.7337 1.60948 15.2663 3.17157 16.8284C4.73367 18.3905 7.26633 18.3905 8.82843 16.8284L10.3284 15.3284C10.719 14.9379 10.719 14.3047 10.3284 13.9142C9.9379 13.5237 9.30474 13.5237 8.91421 13.9142L7.41421 15.4142C6.63316 16.1953 5.36684 16.1953 4.58579 15.4142C3.80474 14.6332 3.80474 13.3668 4.58579 12.5858L7.58579 9.58579Z" fill-rule="evenodd"/></svg>
        <div>
          <div class="text-sm font-bold uppercase tracking-wide">Synology</div>
          <div class="text-xs text-slate-500 group-hover:text-blue-600">synology.home</div>
        </div>
      </div>
    </a>
  </div>
</div>

<div class="mt-6 w-96 md:w-30rem xl:w-48rem">
  <div class="mb-3 text-fuchsia-800 opacity-50 uppercase font-bold text-sm tracking-wider">Network Devices</div>

  <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-y-2 gap-x-2">
    <div class="p-4 pb-3 w-full flex border-2 rounded border-stone-200 text-slate-700 bg-stone-50 hover:border-stone-300">
      <div class="flex">
        <svg class="h-6 w-6 mt-1.5 mr-1.5 opacity-70" fill="currentColor" data-name="Layer 1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M8,6A1,1,0,1,0,7,5,1,1,0,0,0,8,6ZM21,19H14.82A3,3,0,0,0,13,17.18V15h4a3,3,0,0,0,3-3V10a3,3,0,0,0-.78-2A3,3,0,0,0,20,6V4a3,3,0,0,0-3-3H7A3,3,0,0,0,4,4V6a3,3,0,0,0,.78,2A3,3,0,0,0,4,10v2a3,3,0,0,0,3,3h4v2.18A3,3,0,0,0,9.18,19H3a1,1,0,0,0,0,2H9.18a3,3,0,0,0,5.64,0H21a1,1,0,0,0,0-2ZM6,4A1,1,0,0,1,7,3H17a1,1,0,0,1,1,1V6a1,1,0,0,1-1,1H7A1,1,0,0,1,6,6Zm1,9a1,1,0,0,1-1-1V10A1,1,0,0,1,7,9H17a1,1,0,0,1,1,1v2a1,1,0,0,1-1,1Zm5,8a1,1,0,1,1,1-1A1,1,0,0,1,12,21ZM8,10a1,1,0,1,0,1,1A1,1,0,0,0,8,10Z"/></svg>
        <div>
          <div class="text-sm font-bold uppercase tracking-wide">Synology</div>
          <div class="text-xs text-slate-500">192.168.85.134</div>
          <div class="text-xs text-slate-500">storage.home</div>
          <div class="text-xs text-slate-500">synology.home</div>
        </div>
      </div>
    </div>

    <div class="p-4 pb-3 w-full flex border-2 rounded border-stone-200 text-slate-700 bg-stone-50 hover:border-stone-300">
      <div class="flex">
        <svg class="h-6 w-6 mt-1.5 mr-1.5 opacity-70" fill="currentColor" data-name="Layer 1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M8,6A1,1,0,1,0,7,5,1,1,0,0,0,8,6ZM21,19H14.82A3,3,0,0,0,13,17.18V15h4a3,3,0,0,0,3-3V10a3,3,0,0,0-.78-2A3,3,0,0,0,20,6V4a3,3,0,0,0-3-3H7A3,3,0,0,0,4,4V6a3,3,0,0,0,.78,2A3,3,0,0,0,4,10v2a3,3,0,0,0,3,3h4v2.18A3,3,0,0,0,9.18,19H3a1,1,0,0,0,0,2H9.18a3,3,0,0,0,5.64,0H21a1,1,0,0,0,0-2ZM6,4A1,1,0,0,1,7,3H17a1,1,0,0,1,1,1V6a1,1,0,0,1-1,1H7A1,1,0,0,1,6,6Zm1,9a1,1,0,0,1-1-1V10A1,1,0,0,1,7,9H17a1,1,0,0,1,1,1v2a1,1,0,0,1-1,1Zm5,8a1,1,0,1,1,1-1A1,1,0,0,1,12,21ZM8,10a1,1,0,1,0,1,1A1,1,0,0,0,8,10Z"/></svg>
        <div>
          <div class="text-sm font-bold uppercase tracking-wide">Raspberry Pi 3B+</div>
          <div class="text-xs text-slate-500">192.168.86.10</div>
          <div class="text-xs text-slate-500">pi3b.home</div>
        </div>
      </div>
    </div>

    <div class="p-4 pb-3 w-full flex border-2 rounded border-stone-200 text-slate-700 bg-stone-50 hover:border-stone-300">
      <div class="flex">
        <svg class="h-6 w-6 mt-1.5 mr-1.5 opacity-70" fill="currentColor" data-name="Layer 1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M8,6A1,1,0,1,0,7,5,1,1,0,0,0,8,6ZM21,19H14.82A3,3,0,0,0,13,17.18V15h4a3,3,0,0,0,3-3V10a3,3,0,0,0-.78-2A3,3,0,0,0,20,6V4a3,3,0,0,0-3-3H7A3,3,0,0,0,4,4V6a3,3,0,0,0,.78,2A3,3,0,0,0,4,10v2a3,3,0,0,0,3,3h4v2.18A3,3,0,0,0,9.18,19H3a1,1,0,0,0,0,2H9.18a3,3,0,0,0,5.64,0H21a1,1,0,0,0,0-2ZM6,4A1,1,0,0,1,7,3H17a1,1,0,0,1,1,1V6a1,1,0,0,1-1,1H7A1,1,0,0,1,6,6Zm1,9a1,1,0,0,1-1-1V10A1,1,0,0,1,7,9H17a1,1,0,0,1,1,1v2a1,1,0,0,1-1,1Zm5,8a1,1,0,1,1,1-1A1,1,0,0,1,12,21ZM8,10a1,1,0,1,0,1,1A1,1,0,0,0,8,10Z"/></svg>
        <div>
          <div class="text-sm font-bold uppercase tracking-wide">MacBook Pro 14" 2022</div>
          <div class="text-xs text-slate-500">192.168.86.40</div>
          <div class="text-xs text-slate-500">mbp14.home</div>
          <div class="text-xs text-slate-500">macbookpro14.home</div>
        </div>
      </div>
    </div>

    <div class="p-4 pb-3 w-full flex border-2 rounded border-stone-200 text-slate-700 bg-stone-50 hover:border-stone-300">
      <div class="flex">
        <svg class="h-6 w-6 mt-1.5 mr-1.5 opacity-70" fill="currentColor" data-name="Layer 1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M8,6A1,1,0,1,0,7,5,1,1,0,0,0,8,6ZM21,19H14.82A3,3,0,0,0,13,17.18V15h4a3,3,0,0,0,3-3V10a3,3,0,0,0-.78-2A3,3,0,0,0,20,6V4a3,3,0,0,0-3-3H7A3,3,0,0,0,4,4V6a3,3,0,0,0,.78,2A3,3,0,0,0,4,10v2a3,3,0,0,0,3,3h4v2.18A3,3,0,0,0,9.18,19H3a1,1,0,0,0,0,2H9.18a3,3,0,0,0,5.64,0H21a1,1,0,0,0,0-2ZM6,4A1,1,0,0,1,7,3H17a1,1,0,0,1,1,1V6a1,1,0,0,1-1,1H7A1,1,0,0,1,6,6Zm1,9a1,1,0,0,1-1-1V10A1,1,0,0,1,7,9H17a1,1,0,0,1,1,1v2a1,1,0,0,1-1,1Zm5,8a1,1,0,1,1,1-1A1,1,0,0,1,12,21ZM8,10a1,1,0,1,0,1,1A1,1,0,0,0,8,10Z"/></svg>
        <div>
          <div class="text-sm font-bold uppercase tracking-wide">Razer Blade 15</div>
          <div class="text-xs text-slate-500">192.168.86.208</div>
          <div class="text-xs text-slate-500">razer.home</div>
          <div class="text-xs text-slate-500">razer15.home</div>
        </div>
      </div>
    </div>

    <div class="p-4 pb-3 w-full flex border-2 rounded border-stone-200 text-slate-700 bg-stone-50 hover:border-stone-300">
      <div class="flex">
        <svg class="h-6 w-6 mt-1.5 mr-1.5 opacity-70" fill="currentColor" data-name="Layer 1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M8,6A1,1,0,1,0,7,5,1,1,0,0,0,8,6ZM21,19H14.82A3,3,0,0,0,13,17.18V15h4a3,3,0,0,0,3-3V10a3,3,0,0,0-.78-2A3,3,0,0,0,20,6V4a3,3,0,0,0-3-3H7A3,3,0,0,0,4,4V6a3,3,0,0,0,.78,2A3,3,0,0,0,4,10v2a3,3,0,0,0,3,3h4v2.18A3,3,0,0,0,9.18,19H3a1,1,0,0,0,0,2H9.18a3,3,0,0,0,5.64,0H21a1,1,0,0,0,0-2ZM6,4A1,1,0,0,1,7,3H17a1,1,0,0,1,1,1V6a1,1,0,0,1-1,1H7A1,1,0,0,1,6,6Zm1,9a1,1,0,0,1-1-1V10A1,1,0,0,1,7,9H17a1,1,0,0,1,1,1v2a1,1,0,0,1-1,1Zm5,8a1,1,0,1,1,1-1A1,1,0,0,1,12,21ZM8,10a1,1,0,1,0,1,1A1,1,0,0,0,8,10Z"/></svg>
        <div>
          <div class="text-sm font-bold uppercase tracking-wide">MacBook 12" - 2017</div>
          <div class="text-xs text-slate-500">192.168.86.243</div>
          <div class="text-xs text-slate-500">macbook12.home</div>
        </div>
      </div>
    </div>
  </div>
</div>